[workspace]
  resolver = "2"
  members = ["crates/*"]

  [workspace.package]
    edition = "2021"
    homepage = "https://github.com/katoahq/katoa"
    repository = "https://github.com/katoahq/katoa"
    license = "MIT"
    authors = ["Cicada Team", "Katoa Team"]

[profile.release]
  lto = true
